import type { ImageSourcePropType } from 'react-native';

export const decorAssets = {
  cardCloudHills: require('../../assets/generated/card-cloud-hills.png'),
  cardHorizonStar: require('../../assets/generated/card-horizon-star.png'),
  cardNightHills: require('../../assets/generated/card-night-hills.png'),
  cardNightStars: require('../../assets/generated/card-night-stars.png'),
  cardSunsetRound: require('../../assets/generated/card-sunset-round.png'),
  cardWarmAbstract: require('../../assets/generated/card-warm-abstract.png'),
  birds: require('../../assets/generated/decor-birds.png'),
  blobGreen: require('../../assets/generated/decor-blob-green.png'),
  blobNavy: require('../../assets/generated/decor-blob-navy.png'),
  blobPeach: require('../../assets/generated/decor-blob-peach.png'),
  cloudLarge: require('../../assets/generated/decor-cloud-large.png'),
  cloudSmall: require('../../assets/generated/decor-cloud-small.png'),
  dotCream: require('../../assets/generated/decor-dot-cream.png'),
  dotGold: require('../../assets/generated/decor-dot-gold.png'),
  dotNavy: require('../../assets/generated/decor-dot-navy.png'),
  dottedPathStar: require('../../assets/generated/decor-dotted-path-star.png'),
  flowers: require('../../assets/generated/decor-flowers.png'),
  flyingLeaves: require('../../assets/generated/decor-flying-leaves.png'),
  glow: require('../../assets/generated/decor-glow.png'),
  goldenSwoosh: require('../../assets/generated/decor-golden-swoosh.png'),
  grassThin: require('../../assets/generated/decor-grass-thin.png'),
  grassWide: require('../../assets/generated/decor-grass-wide.png'),
  heartCream: require('../../assets/generated/decor-heart-cream.png'),
  heartNavy: require('../../assets/generated/decor-heart-navy.png'),
  heartOrange: require('../../assets/generated/decor-heart-orange.png'),
  heartRibbon: require('../../assets/generated/decor-heart-ribbon.png'),
  hillCloudLeft: require('../../assets/generated/decor-hill-cloud-left.png'),
  hillCloudMiddle: require('../../assets/generated/decor-hill-cloud-middle.png'),
  hillSunset: require('../../assets/generated/decor-hill-sunset.png'),
  leafPair: require('../../assets/generated/decor-leaf-pair.png'),
  leavesSprig: require('../../assets/generated/decor-leaves-sprig.png'),
  moon: require('../../assets/generated/decor-moon.png'),
  mountains: require('../../assets/generated/decor-mountains.png'),
  roadBushes: require('../../assets/generated/decor-road-bushes.png'),
  roadPlants: require('../../assets/generated/decor-road-plants.png'),
  rocks: require('../../assets/generated/decor-rocks.png'),
  shootingStar: require('../../assets/generated/decor-shooting-star.png'),
  softWave: require('../../assets/generated/decor-soft-wave.png'),
  starLarge: require('../../assets/generated/decor-star-large.png'),
  starMedium: require('../../assets/generated/decor-star-medium.png'),
  starSmall: require('../../assets/generated/decor-star-small.png'),
  sun: require('../../assets/generated/decor-sun.png'),
  village: require('../../assets/generated/decor-village.png'),
} satisfies Record<string, ImageSourcePropType>;

export type DecorAssetName = keyof typeof decorAssets;
