create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('android','ios')),
  channel text not null default 'preview' check (channel in ('preview','production')),
  version_name text not null,
  version_code integer not null check (version_code > 0),
  minimum_supported_code integer not null default 1 check (minimum_supported_code > 0),
  title text,
  notes text,
  download_url text,
  is_enabled boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(platform, channel, version_code),
  check (minimum_supported_code <= version_code),
  check (title is null or char_length(title) <= 120),
  check (notes is null or char_length(notes) <= 4000),
  check (download_url is null or char_length(download_url) <= 2000)
);

alter table public.app_releases enable row level security;
revoke all on table public.app_releases from public, anon, authenticated;
grant select on table public.app_releases to anon, authenticated;

create policy app_releases_read_enabled
on public.app_releases
for select
to anon, authenticated
using (is_enabled = true);

create index if not exists app_releases_latest_idx
on public.app_releases(platform, channel, version_code desc)
where is_enabled = true;

insert into public.app_releases (
  platform, channel, version_name, version_code, minimum_supported_code, title, notes, download_url, is_enabled
)
values (
  'android', 'preview', '0.1.1', 2, 1,
  'Голосовые и безопасный экран Android',
  'Голосовые истории, приватный архив, корректные отступы от статус-бара и системной навигации Android.',
  null,
  true
)
on conflict (platform, channel, version_code) do update
set version_name = excluded.version_name,
    minimum_supported_code = excluded.minimum_supported_code,
    title = excluded.title,
    notes = excluded.notes,
    is_enabled = excluded.is_enabled;

create or replace function public.get_latest_app_release(
  p_platform text default 'android',
  p_channel text default 'preview'
) returns table (
  version_name text,
  version_code integer,
  minimum_supported_code integer,
  title text,
  notes text,
  download_url text,
  published_at timestamptz
)
language sql
security invoker
stable
set search_path = pg_catalog, public
as $$
  select r.version_name, r.version_code, r.minimum_supported_code, r.title, r.notes, r.download_url, r.published_at
  from public.app_releases r
  where r.platform = p_platform
    and r.channel = p_channel
    and r.is_enabled = true
  order by r.version_code desc
  limit 1;
$$;

revoke all on function public.get_latest_app_release(text,text) from public;
grant execute on function public.get_latest_app_release(text,text) to anon, authenticated;
